apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stream-counter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-team-1
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: app-team-1/charts/stream-counter
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
